###
GET http://localhost:9000/api/category

### 
GET http://localhost:9000/api/category/6419311f52b7227a58347b73

###
POST http://localhost:9000/api/category
Content-Type: application/json

{
    "category": "Sweeter"
}

###
DELETE http://localhost:9000/api/category/6419311f52b7227a58347b73

###
PUT http://localhost:9000/api/category/6419314d52b7227a58347b7b
Content-Type: application/json

{
    "category": "Boots"
}