###
GET http://localhost:9000/api/user
###
POST http://localhost:9000/api/login
Content-Type: application/json

{
      "password": "lol1",
      "email": "jack3@gmail.com"
}

### 
POST http://localhost:9000/api/user
Content-Type: application/json

{   "firstName": "jack",
    "lastName": "jack",
    "password": "jack123",
    "email": "jack1123@gmail.com",
    "favProduct": ["ahah","eheh"],
    "mostVisitedProduct": ["boots", "sweeters"]
}
###
POST http://localhost:9000/api/userall
Content-Type: application/json

{
      "firstName": "Jack",
      "lastName": "Jack",
      "password": "lol1",
      "email": "jack3@gmail.com"
}

###
POST http://localhost:9000/api/user/641bb9afbe5080aadc094adc
Content-Type: application/json

{
      "password": "lol1",
      "email": "jack3@gmail.com",
      "token": ""
}

###
POST http://localhost:9000/api/users
Content-Type: application/json

{
      "password": "lol1",
      "email": "jack3@gmail.com"
}
